---
title: "Práctica Final Data Driven Security"
author: "Grup CC: Toni Jordan Y Joan Dalmau"
date: "1 de Junio de 2023"
output:
  html_document:
    toc: yes
    number_sections: yes
    toc_float: true
    toc_collapsed: true
    toc_depth: 4
    theme: yeti
  html_notebook:
    number_sections: yes
    theme: spacelab
    toc: yes
    toc_float: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.align = 'center')

library(randomForest)
library(readr)
library(caret)
library(e1071)
library(dplyr)
library(ggplot2)
```

## Carga del dataset
```{r read_data}
data_full <- read_csv("Book1.csv",
                  col_types = cols(SrcBytes = col_integer(),
                                   DstBytes = col_integer(), Land = col_integer(),
                                   WrongFragment = col_integer(), Urgent = col_number(),
                                   Hot = col_number(), NumFailedLogin = col_integer()))
data <- read.csv("Book2.csv",header=T)
```

## Validación del Dataset de muestras

Se valida que el Dataset parcial tiene las muestra suficientes para mantener las mismas proporciones que el Dataset global

```{r verify_data}
# Calcula estadísticas descriptivas para el conjunto de datos completo
full_data_attack_dist <- data_full %>% group_by(Attack) %>%
  summarise(Count = n()) %>%
  mutate(Percentage = Count / sum(Count) * 100)

# Calcula estadísticas descriptivas para la muestra extraída
sample_attack_dist <- data %>% group_by(Attack) %>%
  summarise(Count = n()) %>%
  mutate(Percentage = Count / sum(Count) * 100)

# Combina las distribuciones en una tabla comparativa
comparison_table <- full_data_attack_dist %>%
  full_join(sample_attack_dist, by = "Attack", suffix = c("_FullData", "_Sample")) %>%
  mutate(Difference = abs(Percentage_FullData - Percentage_Sample),
         SignificantlyDifferent = ifelse(Difference > 5, "Yes", "No"))

# Filtra los valores con diferencias relevantes
relevant_differences <- comparison_table %>% filter(Difference > 5)

# Crea un gráfico de barras comparativo con resaltado para valores significativamente diferentes
comparison_plot <- ggplot(comparison_table, aes(x = Attack)) +
  geom_bar(aes(y = Percentage_FullData, fill = SignificantlyDifferent), stat = "identity", alpha = 0.5) +
  geom_bar(aes(y = Percentage_Sample), stat = "identity", fill = "red", alpha = 0.5) +
  labs(x = "Attack", y = "Percentage") +
  scale_y_continuous(labels = scales::percent_format()) +
  ggtitle("Comparativa de Distribución de Ataques") +
  theme_minimal() +
  scale_fill_manual(values = c("Yes" = "yellow", "No" = "blue"))

# Crea un gráfico de barras comparativo solo para las diferencias relevantes
comparison_plot3 <- ggplot(relevant_differences, aes(x = Attack, y = Difference)) +
  geom_bar(stat = "identity", fill = "blue", alpha = 0.5) +
  labs(x = "Attack", y = "Difference") +
  ggtitle("Comparativa de Distribución de Ataques") +
  theme_minimal()

# Imprime la tabla comparativa
print(comparison_table)
print(comparison_plot)
print(comparison_plot3)
```

```{r study_dataset}
# Calcula el número total de casos por cada valor de "Attack"
attack_totals <- sort(table(data$Attack), decreasing = TRUE)
# Elimina el valor "normal" de la tabla de totales del dataset completo
attack_totals <- attack_totals[attack_totals != attack_totals["normal."]]

# Crea una tabla ordenada con los totales
attack_table <- data.frame(Attack = names(attack_totals), Total = as.numeric(attack_totals))
attack_table <- attack_table[order(attack_table$Total, decreasing = TRUE), ]

# Imprime la tabla ordenada
print(attack_table)
```
Count numeric and char variables.
```{r study 2 dataset}
numericVars <- which(sapply(data, is.numeric)) 
numericVarNames <- names(numericVars) 
cat('Hay', length(numericVars), 'variables numéricas')
#Charcol <- names(data[,sapply(data, is.factor)])
#cat('There are', length(Charcol), 'remaining columns with factor values')

# Crear una tabla para almacenar la información del tipo de variables
tipo_variables <- data.frame(Columna = names(data), Tipo = sapply(data, class), stringsAsFactors = FALSE)

# Mostrar la tabla de tipos de variables y validar categoricas
print(tipo_variables)
```

```{r select-processing, echo=TRUE}
# Explore categorical features
#cat_cols <- c("ProtocolType", "Service", "Flag", "Label")

# Print categories in each feature
cat("Training set:\n")
for (col_name in names(data)) {
  if (is.character(data[[col_name]])) {
    unique_cat <- length(unique(data[[col_name]]))
    cat(paste("Feature '", col_name, "' tiene", unique_cat, " categorias\n", sep = ""))
  }
}

cat("\nDistribución de categorias en Service:\n")
cat(sort(table(data$Service), decreasing = TRUE)[1:5], "\n")
```

Esta sección es para completar el estudio de los datos y sus relaciones

# EDA
```{r eda1, echo=TRUE}
# Observation: dst_host_same_src_port_rate has slight effect on the intrusion type.
# for "dst_host_same_src_port_rate" value greater than equal to 1 it can be "probe" and "r2l""
qplot(DstHostSameSrvRate,DstHostSrvCount,colour=Attack,data=data)
```

```{r eda2, echo=TRUE}
# Observation: "flag" is a strong predictor. for flag= "REG" and "S0" it is "dos"
qplot(Service,Flag,colour=Attack,data=data)
```

```{r eda3, echo=TRUE}
# Observation: For duration Greater than 30000 we can see it's 'probe'
# Therefore duration itself is a strong predictor
qplot(Duration,SrcBytes,colour=Attack,data=data)
```

```{r eda4, echo=TRUE}
# Observation: For duration Greater than 30000 we can see it's 'probe'
# Observation: protocol-type "tcp" has "DOS" intrusion type. It is also a strong predictor of "dos" type.
qplot(Service,ProtocolType,colour=Attack,data=data)
```

```{r eda5, echo=TRUE}
# Observation: No such clear identification
qplot(Flag,Land,colour=Attack,data=data)
```

```{r eda6, echo=TRUE}
# Observation: For serror_rate and srv_serror_rate=0 or 1 its "dos" and
# serror_rate between 0.25 to 0.5 its "probe""
qplot(SerrorRate,SrvSerrorRate,colour=Attack,data=data)
```

```{r eda7, echo=TRUE}
# Observation:For duration Greater than 30000 we can see it's 'probe'
qplot(Duration,SrcBytes,colour=Attack,data=data)
```

```{r eda8, echo=TRUE}
# Result: We can clearly see flag is a strong predictor for "dos" type intrusion
A=table(data$Flag,data$Attack)
round(prop.table(A)*100,1)
```

Seción de carga de los diferentes modelos de subset por variables
```{r feature_selection, echo=FALSE}
#original
data1_original <- data[,c("SrcBytes", "DstBytes", "Land", "WrongFragment", "Urgent", "SameSrvRate", "LoggedIn",  "DstHostSameSrvRate", "DstHostSrvCount","Flag","Attack" )]

#pdf
data1_pdf <- data[,c("SrcBytes", "DstBytes", "DstHostSameSrvRate", "Count", "DstHostDiffSrvRate","Attack" )]

#formal LAN
data1_teorico <- data[,c("SrcBytes", "DstBytes", "Land", "WrongFragment", "Urgent", "Hot","NumFailedLogin","Attack" )]

#varianza
data1 <- data[,c("SrcBytes", "DstBytes", "Count", "DstHostSameSrvRate", "DstHostDiffSrvRate", "DstHostSrvDiffHostRate", "LoggedIn","SrvCount", "SerrorRate", "SrvSerrorRate", "RerrorRate", "SrvRerrorRate", "DiffSrvRate","SrvDiffHostRate", "DstHostSrvCount", "DstHostSameSrcPortRate", "DstHostSerrorRate", "DstHostSrvSerrorRate", "DstHostRerrorRate", "DstHostSrvRerrorRate","Attack" )]

data1$Attack <- as.factor(data1$Attack)
data1_original$Attack <- as.factor(data1_original$Attack)
data1_pdf$Attack <- as.factor(data1_pdf$Attack)
data1_teorico$Attack <- as.factor(data1_teorico$Attack)
```

```{r train_test, echo=FALSE}
set.seed(123)
inTrain <- createDataPartition(y=data1$Attack, p=0.2, list=FALSE)
inTrain_original <- createDataPartition(y=data1_original$Attack, p=0.2, list=FALSE)
inTrain_pdf <- createDataPartition(y=data1_pdf$Attack, p=0.2, list=FALSE)
inTrain_teorico <- createDataPartition(y=data1_teorico$Attack, p=0.2, list=FALSE)

training <- data1[inTrain,]
testing <- data1[-inTrain,]
dim <-nrow (training)
dim(training)

training_original <- data1_original[inTrain_original,]
testing_original <- data1_original[-inTrain_original,]
dim <-nrow (training_original)
dim(training_original)

training_pdf <- data1_pdf[inTrain_pdf,]
testing_pdf <- data1_pdf[-inTrain_pdf,]
dim <-nrow (training_pdf)
dim(training_pdf)

training_teorico <- data1_teorico[inTrain_teorico,]
testing_teorico <- data1_teorico[-inTrain_teorico,]
dim <-nrow (training_teorico)
dim(training_teorico)
```

```{r train_random_forest, echo=FALSE}
output.forest <- randomForest(Attack ~ ., data = training, na.action=na.fail)
output.forest_ori <- randomForest(Attack ~ ., data = training_original, na.action=na.fail)
output.forest_pdf <- randomForest(Attack ~ ., data = training_pdf, na.action=na.fail)
output.forest_teo <- randomForest(Attack ~ ., data = training_teorico, na.action=na.fail)
#print(output.forest)
#plot(output.forest)
```

```{r predict, echo=FALSE}
pred <- predict(output.forest,testing)
#str(pred)

pred_ori <- predict(output.forest_ori,testing_original)
pred_pdf <- predict(output.forest_pdf,testing_pdf)
pred_teo <- predict(output.forest_teo,testing_teorico)
#```

#```{r simple_validation, echo=FALSE}
valid <- testing
valid$Attack <- as.character(valid$Attack)
valid$pred <- as.character(pred)
valid$match <- valid$Attack == valid$pred

df <- table(valid$match)
ok <- df[2]/(df[1]+df[2])*100

valid_ori <- testing_original
valid_ori$Attack <- as.character(valid_ori$Attack)
valid_ori$pred <- as.character(pred_ori)
valid_ori$match <- valid_ori$Attack == valid_ori$pred

df_ori <- table(valid_ori$match)
ok_ori <- df_ori[2]/(df_ori[1]+df_ori[2])*100

valid_pdf <- testing_pdf
valid_pdf$Attack <- as.character(valid_pdf$Attack)
valid_pdf$pred <- as.character(pred_pdf)
valid_pdf$match <- valid_pdf$Attack == valid_pdf$pred

df_pdf <- table(valid_pdf$match)
ok_pdf <- df_pdf[2]/(df_pdf[1]+df_pdf[2])*100

valid_teo <- testing_teorico
valid_teo$Attack <- as.character(valid_teo$Attack)
valid_teo$pred <- as.character(pred_teo)
valid_teo$match <- valid_teo$Attack == valid_teo$pred

df_teo <- table(valid_teo$match)
ok_teo <- df_teo[2]/(df_teo[1]+df_teo[2])*100

tabla_resultados <- data.frame(Variable = c("Propuesto", "Enunciado", "Ejemplo_PDF", "Teórico"),
                              Valor = c(ok, ok_ori, ok_pdf, ok_teo))
print(tabla_resultados)
summary(tabla_resultados)
```


